name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres_mi:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      elasticsearch:
        image: elasticsearch:6.8.2
        ports:
        - 9200/tcp

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --cache-dir ~/cache/pip --progress-bar off -r requirements.txt

    - name: Lint source
      run: |
        python -m flake8

    - name: Run tests
      run: |
        python -m pytest -n 4 -p no:sugar --cov --junitxml=test-reports/junit.xml --durations 25
      env:
        ADMIN_OAUTH2_ENABLED: 'False'
        ACTIVITY_STREAM_ACCESS_KEY_ID: some-id
        ACTIVITY_STREAM_SECRET_ACCESS_KEY: some-secret
        DATABASE_URL: postgresql://postgres@postgres:${{ job.services.postgres.ports[5432] }}/datahub
        MI_DATABASE_URL: postgresql://postgres@mi-postgres:${{ job.services.postgres_mi.ports[5432] }}/mi
        DEBUG: 'True'
        DJANGO_SECRET_KEY: changeme
        DJANGO_SETTINGS_MODULE: config.settings.local
        ES_INDEX_PREFIX: test_index
        ES5_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
        PAAS_IP_WHITELIST: 1.2.3.4
        AWS_DEFAULT_REGION: eu-west-2
        AWS_ACCESS_KEY_ID: foo
        AWS_SECRET_ACCESS_KEY: bar
        DEFAULT_BUCKET: baz
        SSO_ENABLED: 'True'
        RESOURCE_SERVER_INTROSPECTION_URL: http://sso/o/introspect/
        RESOURCE_SERVER_AUTH_TOKEN: sso-token
        DIT_EMAIL_DOMAINS: trade.gov.uk,digital.trade.gov.uk
        DATA_HUB_FRONTEND_ACCESS_KEY_ID: frontend-key-id
        DATA_HUB_FRONTEND_SECRET_ACCESS_KEY: frontend-key
